[package]
name = "ekvsb"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]

[dependencies]
byte-unit = "1"
clap = "2"
indicatif = "0.9"
percent-encoding = "1"
rand = "0.5"
rocksdb = "0.10"
serde = "1"
serde_derive = "1"
serde_json = "1"
siphasher = "0.2"
trackable = { version = "0.2", features = ["serialize"] }
